version: 1.0.{build}

image: Visual Studio 2017

environment:
  BOOST_ROOT: C:/Libraries/boost_1_64_0
  GENERATOR: "Visual Studio 14 Win64"
  QT_DIR: C:/Qt/5.11.0/msvc2017_64

configuration:
  - Release

matrix:
  fast_finish: true

install:
  - git submodule init
  - git submodule update

build_script:
  - cmake -G "%GENERATOR%" -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QT_DIR%" -H. -Bbuild
  - cmake --build build --config "%CONFIGURATION%"
